<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Confirmation</name>
   <tag></tag>
   <elementGuidId>715bd596-6c62-42fa-a3b8-bcf8e87374f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.jss1465</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[(text() = 'Confirmation' or . = 'Confirmation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Confirmation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>91641c4c-c273-4bce-be38-0a122c5a7fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss1465</value>
      <webElementGuid>779996d2-f8ac-4c02-b61a-c698b92e668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmation</value>
      <webElementGuid>95c3cd1a-5232-4c8b-a24d-d14fc08fd003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;jss1463&quot;]/div[@class=&quot;jss1464&quot;]/h1[@class=&quot;jss1465&quot;]</value>
      <webElementGuid>7ab11c6d-8739-43f1-9716-c72eaaebe8de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::h1[1]</value>
      <webElementGuid>c056876c-2685-4b96-94b3-3a401abee6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are You Sure To Edit Your Data?'])[1]/preceding::h1[1]</value>
      <webElementGuid>b1971f81-bbc3-4f19-b6aa-9c7b866dc85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::h1[1]</value>
      <webElementGuid>358af0bc-e4e5-4efd-bb69-23c5f595b433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmation']/parent::*</value>
      <webElementGuid>acbf7268-fc0d-44d2-a67c-295d8ac45de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>73f4dddd-2977-4b2e-a648-3e86b36a7c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Confirmation' or . = 'Confirmation')]</value>
      <webElementGuid>a8ba4310-eb1b-4913-83d7-c6690e0d0947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
