<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Confirmation</name>
   <tag></tag>
   <elementGuidId>3ab2d640-fe21-447b-bb8e-2436fb872856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.jss2938</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[(text() = 'Confirmation' or . = 'Confirmation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Confirmation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a787e8c7-060a-4dad-9c1c-7d9f6cfa429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2938</value>
      <webElementGuid>60e8b2ba-7462-43a3-bf58-53b305083213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmation</value>
      <webElementGuid>7127a57a-1e0c-4435-8391-5be0a5049742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;jss2936&quot;]/div[@class=&quot;jss2937&quot;]/h1[@class=&quot;jss2938&quot;]</value>
      <webElementGuid>a3dadb85-c84a-43ca-baf6-4c980163c3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::h1[1]</value>
      <webElementGuid>d5260df1-1141-403c-976b-3536804278f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are You Sure Want To Block Your Data?'])[1]/preceding::h1[1]</value>
      <webElementGuid>ef79f27e-d2bc-4398-987c-05da17336126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::h1[1]</value>
      <webElementGuid>8538fb19-0905-4be9-9653-12133734a747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmation']/parent::*</value>
      <webElementGuid>9469826c-9227-4015-92ab-4a95b6b75f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>349970b7-08b3-46f8-aec4-d8a42a40e9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Confirmation' or . = 'Confirmation')]</value>
      <webElementGuid>8c272d10-4c8f-48f9-be5a-9a74a6ce0f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
