<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Segmentation Settings</name>
   <tag></tag>
   <elementGuidId>cd38e083-e31b-43dc-bf6e-50b5843d2c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jss15753</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Segmentation Settings&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2dec1b49-63b5-4473-9529-452de9a0239c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss15753</value>
      <webElementGuid>12a2cfc0-3b06-4a8e-87a9-b26c1a2b9443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Segmentation Settings</value>
      <webElementGuid>70dbbcdb-7bba-4089-9614-509be8b53832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;jss15732&quot;]/div[@class=&quot;jss15733&quot;]/div[1]/div[2]/div[@class=&quot;jss15751&quot;]/div[1]/div[@class=&quot;jss15753&quot;]</value>
      <webElementGuid>c813c2f1-70b9-4402-8292-8ad5204c40dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>dc8d4d11-9629-4efb-adbc-353f7af7f5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segmentation Settings'])[1]/following::div[5]</value>
      <webElementGuid>8fbbf33a-377a-4c39-b8bf-b0aee2770625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management Token'])[2]/following::div[6]</value>
      <webElementGuid>116d86dd-8dad-43a7-9047-529b6f66cbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Segmentation :'])[1]/preceding::div[1]</value>
      <webElementGuid>1e37936b-01aa-4711-8c4c-07e98ec69212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TempRio'])[1]/preceding::div[2]</value>
      <webElementGuid>571fb030-3b28-4460-8094-ff2f300c9f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>3a675ad2-9bd2-401e-a438-0af6120b164a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Segmentation Settings' or . = 'Segmentation Settings')]</value>
      <webElementGuid>933194a9-2ba7-4880-a031-21748c67c06f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
