<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_CurrSegmentation</name>
   <tag></tag>
   <elementGuidId>888c4408-d99b-45fe-9378-ec5bd4958d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jss15756</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;TempRio&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68644803-cbda-4e3a-afbc-7d9b5e9cd9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss15756</value>
      <webElementGuid>3d3c6616-2dcf-4bd6-96de-3db10164d2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TempRio</value>
      <webElementGuid>ff3e5806-b6df-41d1-a6cd-e3e3258f1c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;jss15732&quot;]/div[@class=&quot;jss15733&quot;]/div[1]/div[2]/div[@class=&quot;jss15751&quot;]/div[1]/div[@class=&quot;jss15754&quot;]/div[1]/div[@class=&quot;jss15756&quot;]</value>
      <webElementGuid>8bc7f0a3-f748-4e6d-aca8-5c09fff1ac11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>18475b47-1072-4b55-aec3-fed4aabed957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Segmentation :'])[1]/following::div[1]</value>
      <webElementGuid>90487feb-5ea2-4b3b-ae7f-1b865e0f1d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segmentation Settings'])[2]/following::div[4]</value>
      <webElementGuid>5166899e-760b-4f48-8430-2a8c47186bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select New Segmentation'])[1]/preceding::div[1]</value>
      <webElementGuid>48f6ef81-2aba-4243-8334-49ece293d8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[4]</value>
      <webElementGuid>4cd2b04a-6cbb-42ef-8f42-6e187b55e23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TempRio']/parent::*</value>
      <webElementGuid>2c334441-82b9-42bf-8b08-a17cc7ba79f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>0cbc6702-fe4d-4e82-b256-96ee6fda35d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TempRio' or . = 'TempRio')]</value>
      <webElementGuid>053071a1-5f23-450e-a665-0270cf5a23fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
