<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Account List</name>
   <tag></tag>
   <elementGuidId>49388c2b-f4a6-4122-a870-c1906e4c76da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jss5859</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/section/section/main/div[2]/div[2]/div/div[2]/form/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1401880019680&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77931e2d-fde4-410f-bcbd-4743476af03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss5859</value>
      <webElementGuid>6a25cb18-d655-4715-9f83-a0ed211b7907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1401880019680</value>
      <webElementGuid>df1b134f-4b1d-4eaf-9fe9-dbd05b16b214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;jss5836&quot;]/div[@class=&quot;jss5837&quot;]/div[1]/div[2]/form[1]/div[@class=&quot;MuiPaper-root jss5855 MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;jss5857&quot;]/div[@class=&quot;MuiPaper-root content MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[2]/div[@class=&quot;jss5859&quot;]</value>
      <webElementGuid>6a399632-1606-4d93-9ccb-dea6024d1776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/form/div/div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>c7b7a201-8f5c-4f0d-8b77-1214cb4d0ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tab Bisnis Perorangan'])[1]/following::div[1]</value>
      <webElementGuid>65993693-6ed7-4189-b6d4-2fe484279c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Account Limit'])[1]/following::div[10]</value>
      <webElementGuid>fcd3f1de-e1cb-4fe3-859e-4a0b4f154510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/preceding::div[1]</value>
      <webElementGuid>aff6e088-492c-4bc1-ac85-a628e0867793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Limits :'])[1]/preceding::div[3]</value>
      <webElementGuid>ac2de451-4916-4674-85ec-3fc825f09ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>1694b1fb-4d39-4bfe-9d6c-ed237745353c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1401880019680' or . = '1401880019680')]</value>
      <webElementGuid>056db0e1-6da1-42ab-94e1-0970bf1b9837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
