<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Corporate ID</name>
   <tag></tag>
   <elementGuidId>e585b26b-6660-4a4a-84d8-002b0c2387c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/section/section/main/div[2]/div[2]/div/div[2]/div/div[1]/div[1]/div/div/div[2]/div/div[1]/div[3]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Saving&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>efceb41d-e052-42e8-8bb3-0309a97786f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2395</value>
      <webElementGuid>2d0a2755-3838-4170-b0b9-edfdd52a40f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saving</value>
      <webElementGuid>a712598b-44f5-4aec-b5d8-363f41d0de9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;jss2365&quot;]/div[@class=&quot;jss2366&quot;]/div[1]/div[2]/div[@class=&quot;jss2384&quot;]/div[@class=&quot;jss2385&quot;]/div[1]/div[1]/div[@class=&quot;jss2390&quot;]/div[@class=&quot;jss2399&quot;]/div[1]/div[@class=&quot;MuiGrid-root MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6&quot;]/div[2]/span[@class=&quot;jss2395&quot;]</value>
      <webElementGuid>bd99e14c-a7c2-4ea7-ab43-a42c0ca20e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div[2]/span</value>
      <webElementGuid>7b179cbb-3d32-4813-865b-846ab60780d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Type :'])[1]/following::span[1]</value>
      <webElementGuid>224f0536-7afe-4dea-9740-eb76f304adad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Number :'])[1]/following::span[3]</value>
      <webElementGuid>e0ad59de-7f78-4465-bc38-843892f23737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Field Profile'])[1]/preceding::span[1]</value>
      <webElementGuid>41867ec1-f240-47a6-87ba-e8b90ee685af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate ID :'])[1]/preceding::span[1]</value>
      <webElementGuid>142b694b-3059-4b4b-b27e-b100cb23ad44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saving']/parent::*</value>
      <webElementGuid>9da91e5d-c1aa-430d-ade7-0a93b744c995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>5aef0e1d-410c-473d-a9f8-c86a2d3884c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Saving' or . = 'Saving')]</value>
      <webElementGuid>01f84711-82fb-4e2b-93c1-4d025579dfc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
