<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Business Name</name>
   <tag></tag>
   <elementGuidId>d3e91bdf-1a1e-4309-a70e-be65cfe22cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/section/section/main/div[2]/div[2]/div/div[2]/div/div[1]/div[1]/div/div/div[2]/div/div[1]/div[4]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Saving&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50931ec1-3b50-4ea1-9d84-c4c0ae396b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2395</value>
      <webElementGuid>086ed0f0-8769-492e-9c01-a871c8b976c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saving</value>
      <webElementGuid>66ebae67-38fa-429a-8628-0dcafab7c63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;jss2365&quot;]/div[@class=&quot;jss2366&quot;]/div[1]/div[2]/div[@class=&quot;jss2384&quot;]/div[@class=&quot;jss2385&quot;]/div[1]/div[1]/div[@class=&quot;jss2390&quot;]/div[@class=&quot;jss2399&quot;]/div[1]/div[@class=&quot;MuiGrid-root MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6&quot;]/div[2]/span[@class=&quot;jss2395&quot;]</value>
      <webElementGuid>a4766469-1ba1-4565-be8d-1e2895b94ad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div[2]/span</value>
      <webElementGuid>4d4b6b33-bf12-4c89-a598-43d76958afe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Type :'])[1]/following::span[1]</value>
      <webElementGuid>ee97e59d-47fc-4192-aa07-27f1354dd428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Number :'])[1]/following::span[3]</value>
      <webElementGuid>0204c988-f116-4d09-9d44-b2476205c919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Field Profile'])[1]/preceding::span[1]</value>
      <webElementGuid>b6ac07aa-3bcc-4701-b0e8-07e63bd9fb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate ID :'])[1]/preceding::span[1]</value>
      <webElementGuid>488caea4-c239-41dc-95c6-9ecc52b3a02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saving']/parent::*</value>
      <webElementGuid>5d594f89-91e0-4fb5-b831-cfbd8c22449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>c1999f66-4b60-4044-9c9c-499fc660d3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Saving' or . = 'Saving')]</value>
      <webElementGuid>c9eecff0-9d2a-400b-adc8-e15bfe02f148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
