<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Company Details</name>
   <tag></tag>
   <elementGuidId>213e77d3-a2a5-4f67-bc5f-273b4724dfbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.jss2372</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div[2]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Company Details&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7b9500d7-3a58-416a-b648-af6c0cd3e529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2372</value>
      <webElementGuid>b0afad78-a08f-4277-8ecc-0751ae0fc4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company Details</value>
      <webElementGuid>11870fab-dda8-42c8-bbff-7f0552b88348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;jss2365&quot;]/div[@class=&quot;jss2380&quot;]/h1[@class=&quot;jss2372&quot;]</value>
      <webElementGuid>f66e7f5f-a150-442f-b8f7-17cee83dd6d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/div/h1</value>
      <webElementGuid>1ed310c8-3c1c-4c23-8c2e-4e4b19150621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin, maker, approver'])[1]/following::h1[1]</value>
      <webElementGuid>08520af6-868f-4403-8a5c-154321548e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mii.rioneda'])[1]/following::h1[1]</value>
      <webElementGuid>e04083e9-e2dc-4316-8db9-3a31004fb16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Usaha Digital'])[1]/preceding::h1[1]</value>
      <webElementGuid>5733ce29-7834-4cd7-a9e1-9ed744159d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Authorization'])[1]/preceding::h1[2]</value>
      <webElementGuid>cc60cdd1-7053-4f98-8104-2f0fd6a0faf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company Details']/parent::*</value>
      <webElementGuid>00d9a346-9a67-4ba4-8448-6074eb7c8883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>8f0263e8-156a-410a-bb59-0da37c2d0722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Company Details' or . = 'Company Details')]</value>
      <webElementGuid>305a4192-ed4c-4fcf-8ddd-9cd585a66d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
