<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone Number_phoneNumber</name>
   <tag></tag>
   <elementGuidId>56cce597-078a-46e9-a9de-ba455dbd2ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phoneNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;8123456789&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5e783bc-9a2f-42c3-b9e8-edc44b91ca6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>/portal/static/media/p62.91444c20.svg</value>
      <webElementGuid>1a20ab68-424e-4235-ab11-5da44ea8fedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>8123456789</value>
      <webElementGuid>0cbd1156-1ae4-4cf2-99a4-c70293da8cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>f8921d74-e71b-44f1-8da4-5dae8cd492b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input jss3406</value>
      <webElementGuid>aef78aa9-0ccb-4a2e-b1ba-963c71a8fc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97d2c9cb-4383-4708-aeb8-0925531dd81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8213 2102 033</value>
      <webElementGuid>c9c8ea84-a218-48d8-ae38-3455f5c56828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[2]/form[1]/div[@class=&quot;jss2890&quot;]/div[@class=&quot;jss2891&quot;]/div[@class=&quot;jss2894&quot;]/div[@class=&quot;jss2899&quot;]/div[4]/div[2]/div[@class=&quot;inputGroup&quot;]/div[@class=&quot;jss2820&quot;]/div[1]/div[@class=&quot;jss3402&quot;]/input[@class=&quot;ant-input jss3406&quot;]</value>
      <webElementGuid>3b27a838-86d0-4ca7-b604-3d719c0be4d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phoneNumber']</value>
      <webElementGuid>eb78bd90-0815-4247-9185-b7588b858211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/form/div/div[2]/div/div[2]/div[4]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>aefc42e3-6bdd-43b1-ac82-8f0cb4f83db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>85774dc6-655c-407c-bd90-d7bcd03dba43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '8123456789' and @name = 'phoneNumber' and @type = 'text']</value>
      <webElementGuid>e6b3aabc-112c-4881-8991-40d82a1ae76d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
