<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_identityNumber</name>
   <tag></tag>
   <elementGuidId>7950b1b0-39ee-4e8b-b97e-33590fe493f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;identityNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='identityNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your NIK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcf08bf0-dfd9-4e92-86e8-6bba36e67bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your NIK</value>
      <webElementGuid>f2b1bfb9-e794-4b42-85e1-1a376d89c2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>0eda09d8-aa0c-4d77-b480-b261da023964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identityNumber</value>
      <webElementGuid>7f08f32b-02a1-48e5-a0ab-910e11759335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input jss3232</value>
      <webElementGuid>13849002-a271-4dcf-90a6-dc09b1a39ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c0afdfb-ac7e-432f-9087-6bd81a6068c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3333313132314129</value>
      <webElementGuid>ec151108-8600-4843-9615-fb8056f615f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[2]/form[1]/div[@class=&quot;jss2890&quot;]/div[@class=&quot;jss2891&quot;]/div[@class=&quot;jss2894&quot;]/div[@class=&quot;jss2899&quot;]/div[3]/div[2]/div[@class=&quot;inputGroup&quot;]/div[@class=&quot;jss2820&quot;]/input[@class=&quot;ant-input jss3232&quot;]</value>
      <webElementGuid>b18a6fc1-7138-4aee-ae8f-21078744722c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='identityNumber']</value>
      <webElementGuid>387fbd7a-7eec-4043-9b6c-d561c5a707c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/form/div/div[2]/div/div[2]/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>b78714c2-2d86-4009-afd2-e5149cf309d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>72fe305f-ab8d-4e03-8641-41537a9ff58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your NIK' and @name = 'identityNumber' and @type = 'text']</value>
      <webElementGuid>57281892-75db-494c-b4f7-920c3965e04e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
