<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Userforlogout</name>
   <tag></tag>
   <elementGuidId>6bb88970-6bd0-44f6-92b3-ad45d5dcdd20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.MuiAvatar-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div/header/div/div/div/div/div/span/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;AV&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dee1ce71-34bb-485f-b001-cfb0350d9cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AV</value>
      <webElementGuid>3490d249-9a53-439f-bdb1-642d1ab0de41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/portal/static/media/mhidayat.ad3d7c35.png</value>
      <webElementGuid>a244f56f-9686-47fc-9c6e-3ce68c6ad06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-img</value>
      <webElementGuid>3b37bfca-fcd0-4c67-9df8-f7a998de33f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[1]/header[@class=&quot;MuiPaper-root MuiAppBar-root MuiAppBar-positionFixed MuiAppBar-colorPrimary jss990 mui-fixed MuiPaper-elevation4&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-regular MuiToolbar-gutters&quot;]/div[@class=&quot;jss992&quot;]/div[@class=&quot;jss993&quot;]/div[1]/div[@class=&quot;jss994&quot;]/span[@class=&quot;MuiBadge-root&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular jss995&quot;]/img[@class=&quot;MuiAvatar-img&quot;]</value>
      <webElementGuid>23ae0816-9ada-4f89-9ec6-319400aa935a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/header/div/div/div/div/div/span/div/img</value>
      <webElementGuid>ba116236-f975-448b-9c65-bd541e79db25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AV']</value>
      <webElementGuid>ba0d29c1-3ead-473d-89cf-7d948603c693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/img</value>
      <webElementGuid>2d71791a-1b2d-4d29-b1f0-852a8bfcd6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'AV' and @src = '/portal/static/media/mhidayat.ad3d7c35.png']</value>
      <webElementGuid>fef98cf7-2ca3-4d13-83ba-2365d63bfca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
