<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Corporate</name>
   <tag></tag>
   <elementGuidId>1eaec1e4-f96d-48f4-9c68-c53db9c34715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.ant-radio-wrapper.ant-radio-wrapper-checked.jss23830 > span:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/div/div/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Corporate&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9176eb40-5b66-4ec0-84ea-643601250468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate</value>
      <webElementGuid>dab76bd2-b64a-48fd-a975-c4ef568cd2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;jss23647&quot;]/div[@class=&quot;jss23648&quot;]/div[1]/div[2]/div[@class=&quot;jss23805&quot;]/div[@class=&quot;jss23806&quot;]/div[1]/div[1]/div[@class=&quot;jss23811&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-1&quot;]/div[2]/div[@class=&quot;MuiBox-root jss23787&quot;]/div[1]/div[@class=&quot;ant-radio-group ant-radio-group-outline ant-radio-group-large&quot;]/label[@class=&quot;ant-radio-wrapper ant-radio-wrapper-checked jss23830&quot;]/span[2]</value>
      <webElementGuid>8778070d-bf01-4d8c-ab45-d135246dcb18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div[2]/div[2]/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/div/div/label/span[2]</value>
      <webElementGuid>7dcf40c0-06d3-4f04-a975-86ef4d6e659e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Displays a list of transfer recipients by user.'])[1]/following::span[3]</value>
      <webElementGuid>06bef320-abfa-45fd-b313-75632bf692a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::span[3]</value>
      <webElementGuid>f6af5f7d-0622-4e70-bb87-adf8b5dcadb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Displays a list of transfer recipients by corporate.'])[1]/preceding::span[1]</value>
      <webElementGuid>be18e1a9-3696-466f-9aec-727b7ddea8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::span[1]</value>
      <webElementGuid>3e83bf35-b7d9-4e6c-a4f1-da357051aa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corporate']/parent::*</value>
      <webElementGuid>f80893b6-219c-4fb7-b449-c0414296ee74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/span[2]</value>
      <webElementGuid>33e4fd7a-10b2-47c9-88c8-d9758315d441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Corporate' or . = 'Corporate')]</value>
      <webElementGuid>3358f505-09e2-4a11-adb0-af488ab96830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
